export const PRODUCTS = [
  {
    slug: 'control-gastos',
    status: 'available',
    url: 'https://saascontrolgastos.vercel.app',
    es: {
      name: 'Control de Gastos',
      tagline: 'Registra, aprueba y exporta los gastos de tu empresa desde un solo lugar.',
      description: 'Olvídate de las hojas de cálculo y de los recibos perdidos: tu equipo registra los gastos desde el celular, tú los apruebas con un clic y exportas reportes listos para tu contador.',
      features: [
        'Registro de gastos con foto del recibo o factura',
        'Flujo de aprobaciones para equipos de trabajo',
        'Dashboard con gráficas por categoría y mes',
        'Exportación a Excel y PDF lista para el contador',
        'Reportes personalizados con logo y NIT de tu empresa',
        'Planes y pagos en pesos colombianos (PSE, Nequi, Bancolombia)',
      ],
      audience: 'Empresas, negocios familiares e independientes que necesitan saber a dónde se va su dinero sin complicarse con procesos contables.',
      price: 'Desde $29.000 COP/mes · Prueba gratis 14 días · Sin tarjeta',
    },
    en: {
      name: 'Expense Control',
      tagline: 'Record, approve and export your company expenses from one place.',
      description: 'Forget spreadsheets and lost receipts: your team records expenses from their phone, you approve them with one click and export reports ready for your accountant.',
      features: [
        'Expense recording with receipt or invoice photo',
        'Approval workflow for work teams',
        'Dashboard with charts by category and month',
        'Excel and PDF export ready for your accountant',
        'Customized reports with your company logo and tax ID',
        'Plans and payments in Colombian pesos (PSE, Nequi, Bancolombia)',
      ],
      audience: 'Companies, family businesses and independent professionals who need to know where their money goes without getting tangled up in accounting processes.',
      price: 'From $29,000 COP/month · 14-day free trial · No credit card',
    },
  },
  {
    slug: 'nomina',
    status: 'development',
    es: {
      name: 'Nómina',
      tagline: 'Nómina electrónica DIAN, novedades y desprendibles sin dolores de cabeza.',
      description: 'Liquida la nómina de tu equipo cumpliendo la normativa colombiana: novedades, incapacidades, horas extra y desprendibles automáticos, todo en línea y sin errores de cálculo.',
      features: [
        'Nómina electrónica compatible con la DIAN',
        'Liquidación de novedades, incapacidades y vacaciones',
        'Desprendibles de pago digitales para cada empleado',
        'Provisión automática de prestaciones sociales',
        'Reportes de costos laborales por área o sede',
      ],
      audience: 'Pequeñas y medianas empresas que pagan nómina en Colombia y quieren cumplir con la DIAN sin depender de cálculos manuales.',
      price: null,
    },
    en: {
      name: 'Payroll',
      tagline: 'DIAN electronic payroll, leave tracking and payslips without headaches.',
      description: 'Run your team payroll in line with Colombian regulations: leave, sick days, overtime and automatic payslips, all online and free of calculation errors.',
      features: [
        'Electronic payroll compliant with DIAN requirements',
        'Calculation of leave, sick days and vacations',
        'Digital payslips for every employee',
        'Automatic accrual of social benefits',
        'Labor cost reports by area or branch',
      ],
      audience: 'Small and medium-sized companies running payroll in Colombia that want to stay DIAN-compliant without manual calculations.',
      price: null,
    },
  },
  {
    slug: 'inventarios',
    status: 'development',
    es: {
      name: 'Inventarios',
      tagline: 'Controla tu inventario en tiempo real, bodegas y movimientos.',
      description: 'Sabe siempre cuánto stock tienes, dónde está y cuándo reponerlo. Entradas, salidas y transferencias entre bodegas con trazabilidad completa de cada movimiento.',
      features: [
        'Stock en tiempo real por producto y bodega',
        'Entradas, salidas y transferencias con trazabilidad',
        'Alertas de stock mínimo y sugerencias de reposición',
        'Códigos de barra y referencia por producto',
        'Valorización del inventario (costo promedio)',
      ],
      audience: 'Comercios, distribuidoras y talleres que necesitan evitar ventas perdidas por falta de inventario o capital detenido en excedentes.',
      price: null,
    },
    en: {
      name: 'Inventory',
      tagline: 'Control your inventory in real time, warehouses and movements.',
      description: 'Always know how much stock you have, where it is and when to replenish it. Ins, outs and warehouse transfers with full traceability of every movement.',
      features: [
        'Real-time stock by product and warehouse',
        'Ins, outs and transfers with full traceability',
        'Low-stock alerts and replenishment suggestions',
        'Barcodes and product references',
        'Inventory valuation (average cost)',
      ],
      audience: 'Retailers, distributors and workshops that need to avoid lost sales from stockouts or capital tied up in excess inventory.',
      price: null,
    },
  },
  {
    slug: 'recursos-humanos',
    status: 'development',
    es: {
      name: 'Recursos Humanos',
      tagline: 'Contratos, vacaciones, dotaciones y expedientes de tu equipo.',
      description: 'Centraliza la información de tus colaboradores: contratos, documentos, ausencias y dotaciones en un solo lugar, con alertas de vencimientos y solicitudes en línea.',
      features: [
        'Expediente digital por empleado con documentos',
        'Control de contratos con alertas de vencimiento',
        'Gestión de vacaciones, permisos y ausencias',
        'Registro de dotaciones y entregas',
        'Solicitudes del equipo con flujo de aprobación',
      ],
      audience: 'Empresas con equipos de 5 a 100 personas que hoy gestionan su talento humano entre carpetas, correos y papelera llena de formularios.',
      price: null,
    },
    en: {
      name: 'Human Resources',
      tagline: 'Contracts, vacations, uniforms and personnel files for your team.',
      description: 'Centralize your people information: contracts, documents, absences and equipment assignments in one place, with expiry alerts and online requests.',
      features: [
        'Digital personnel file with document storage',
        'Contract tracking with expiration alerts',
        'Vacation, permits and absence management',
        'Uniform and equipment assignment records',
        'Employee requests with approval workflow',
      ],
      audience: 'Companies with teams of 5 to 100 people who currently manage HR through folders, emails and piles of paper forms.',
      price: null,
    },
  },
  {
    slug: 'finanzas-contabilidad',
    status: 'soon',
    es: {
      name: 'Finanzas y Contabilidad',
      tagline: 'Flujo de caja, presupuestos e indicadores de tu empresa.',
      description: 'Toma decisiones con números claros: flujo de caja proyectado, presupuestos por área e indicadores financieros actualizados, sin esperar el cierre de mes.',
      features: [
        'Flujo de caja con proyección semanal y mensual',
        'Presupuestos por área con comparativo real vs. plan',
        'Indicadores financieros clave en un tablero',
        'Cuentas por cobrar y por pagar consolidadas',
        'Exportes listos para tu contador público',
      ],
      audience: 'Dueños de empresa que quieren entender la salud financiera de su negocio sin ser contadores y sin depender de reportes atrasados.',
      price: null,
    },
    en: {
      name: 'Finance & Accounting',
      tagline: 'Cash flow, budgets and business indicators.',
      description: 'Make decisions with clear numbers: projected cash flow, budgets per area and up-to-date financial indicators, without waiting for month-end close.',
      features: [
        'Cash flow with weekly and monthly projections',
        'Area budgets with actual vs. plan comparison',
        'Key financial indicators on one dashboard',
        'Consolidated accounts receivable and payable',
        'Exports ready for your public accountant',
      ],
      audience: 'Business owners who want to understand their company\'s financial health without being accountants or relying on outdated reports.',
      price: null,
    },
  },
  {
    slug: 'crm-ventas',
    status: 'soon',
    es: {
      name: 'CRM y Ventas',
      tagline: 'Clientes, cotizaciones y seguimiento de oportunidades.',
      description: 'No pierdas más ventas por olvidos: registra clientes, envía cotizaciones profesionales y dale seguimiento a cada oportunidad hasta cerrarla.',
      features: [
        'Base de datos centralizada de clientes y contactos',
        'Cotizaciones rápidas con plantillas personalizables',
        'Pipeline visual de oportunidades por etapa',
        'Recordatorios de seguimiento y tareas comerciales',
        'Reportes de cumplimiento de metas de venta',
      ],
      audience: 'Equipos comerciales pequeños y medianos, agentes independientes y empresas que venden por cotización y quieren ordenar su proceso.',
      price: null,
    },
    en: {
      name: 'CRM & Sales',
      tagline: 'Customers, quotes and opportunity tracking.',
      description: 'Stop losing sales to forgetfulness: register customers, send professional quotes and follow up on every opportunity until it closes.',
      features: [
        'Centralized customer and contact database',
        'Quick quotes with customizable templates',
        'Visual opportunity pipeline by stage',
        'Follow-up reminders and sales tasks',
        'Sales goal achievement reports',
      ],
      audience: 'Small and medium sales teams, independent agents and quote-driven companies that want to bring order to their sales process.',
      price: null,
    },
  },
  {
    slug: 'compras-proveedores',
    status: 'soon',
    es: {
      name: 'Compras y Proveedores',
      tagline: 'Órdenes de compra, proveedores y cuentas por pagar.',
      description: 'Organiza todo el ciclo de compras: solicitudes, órdenes, recepción y pago a proveedores, con historial completo y control de lo que debes y a quién.',
      features: [
        'Maestro de proveedores con condiciones de pago',
        'Órdenes de compra con flujo de aprobación',
        'Recepción parcial o total de mercancías',
        'Calendario de cuentas por pagar por vencer',
        'Historial de compras y comparativo de precios',
      ],
      audience: 'Negocios que compran mercancía o insumos con frecuencia y necesitan negociar mejor, pagar a tiempo y no perder documentos.',
      price: null,
    },
    en: {
      name: 'Purchasing & Suppliers',
      tagline: 'Purchase orders, suppliers and accounts payable.',
      description: 'Organize the entire purchasing cycle: requests, orders, receiving and supplier payments, with complete history and control of what you owe and to whom.',
      features: [
        'Supplier master file with payment terms',
        'Purchase orders with approval workflow',
        'Partial or full goods receiving',
        'Accounts payable calendar by due date',
        'Purchase history and price comparison',
      ],
      audience: 'Businesses that buy goods or supplies frequently and need to negotiate better, pay on time and never lose documents again.',
      price: null,
    },
  },
]

export const STATUS = {
  available: { es: 'Disponible', en: 'Available' },
  development: { es: 'En desarrollo', en: 'In development' },
  soon: { es: 'Próximamente', en: 'Coming soon' },
}

export const productosPage = {
  es: {
    label: 'Productos digitales',
    title: 'Software listo para trabajar por ti',
    subtitle: 'Herramientas SaaS diseñadas para la operación diaria de las empresas colombianas. Empieza con la que necesitas hoy y crece con el ecosistema ALMYDEV.',
    seoTitle: 'Productos digitales ALMYDEV | Software empresarial',
    seoDescription: 'Productos digitales SaaS de ALMYDEV: Control de Gastos disponible ahora; Nómina, Inventarios, Recursos Humanos, Finanzas, CRM y Compras en camino.',
    knowMore: 'Conocer más',
    knowLess: 'Ver menos',
    tryNow: 'Probar ahora',
    comingSoonBtn: 'Muy pronto',
    soonBtn: 'Próximamente',
    audienceTitle: '¿Para quién es?',
    priceTba: 'Precio por anunciar',
    availableCount: 'disponible ahora',
    pipelineNote: 'Los productos en desarrollo y próximos se construyen escuchando a empresarios como tú. ¿Necesitas alguno primero? Cuéntanos en el formulario de contacto.',
  },
  en: {
    label: 'Digital products',
    title: 'Software ready to work for you',
    subtitle: 'SaaS tools designed for the daily operation of Colombian companies. Start with the one you need today and grow with the ALMYDEV ecosystem.',
    seoTitle: 'ALMYDEV Digital Products | Business software',
    seoDescription: 'ALMYDEV digital SaaS products: Expense Control available now; Payroll, Inventory, Human Resources, Finance, CRM and Purchasing on the way.',
    knowMore: 'Learn more',
    knowLess: 'Show less',
    tryNow: 'Try it now',
    comingSoonBtn: 'Coming soon',
    soonBtn: 'Coming soon',
    audienceTitle: 'Who is it for?',
    priceTba: 'Price to be announced',
    availableCount: 'available now',
    pipelineNote: 'Products in development and coming soon are built by listening to business owners like you. Need one of them first? Tell us through the contact form.',
  },
}
